spring:
  profiles.active: dev
  main:
    banner-mode: off
logging.level.org.apache.catalina.core: ERROR

conductor:
  server.url: ${ORKES_URI}
  security.client:
    key-id: ${ORKES_KEY_ID}
    secret: ${ORKES_SECRET}
