spring:
  profiles.active: dev
  main:
    banner-mode: off
logging.level:
  ROOT: ERROR
  io.orkes: INFO
  space.yong: INFO

conductor:
  server.url: https://play.orkes.io/api
  security.client:
    key-id: ${ORKES_KEY_ID}
    secret: ${ORKES_SECRET}
