conductor:
  server.url: ${ORKES_URI}
  security.client:
    key-id: ${ORKES_KEY_ID}
    secret: ${ORKES_SECRET}

spring.main.banner-mode: off
logging.level:
  org.apache.catalina.core: ERROR
  org.springframework.boot.web.embedded.tomcat: ERROR
  org.springframework.boot.web.servlet.context: ERROR
  com.netflix.conductor.client.automator: ERROR
